main: net.okocraft.foliaregionvisualizer.FoliaRegionVisualizerPlugin
name: FoliaRegionVisualizer
version: ${projectVersion}
authors: [ "lazy_gon", "Siroshun09"]
api-version: 1.19
depend: [ "BlueMap" ]
folia-supported: true
